package Views;

import Controllers.StudentController;
import Models.RoundedBorder;
import Models.ScrollPaneWin11;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.ArrayList;

public class JoinClass extends JFrame {

    /**
     * Creates new form JoinClass
     */
    public JoinClass(String studentName) throws SQLException, ClassNotFoundException {
        this.studentName = studentName;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() throws SQLException, ClassNotFoundException {

        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jPanel2 = new JPanel();
        jScrollPane1 = new ScrollPaneWin11();

        studentController = new StudentController();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Join Class");
        setMinimumSize(new Dimension(728, 781));

        jPanel1.setBackground(new Color(91, 8, 136));

        jLabel1.setFont(new Font("Snap ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new Color(255, 255, 255));
        jLabel1.setText("TechTeach - Join Class");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(19, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18))
        );

        jPanel2.setBackground(new Color(255, 255, 255));
        jPanel2.setMinimumSize(new Dimension(728, 781));

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 728, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 781, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel2);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        ArrayList<ArrayList<String>> classes = new ArrayList<>(studentController.getAllClasses(studentName));

        if (!classes.isEmpty()){

            jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));

            jPanel2.add(Box.createVerticalStrut(10));
            JLabel label = new JLabel("Click On The Classname To Join Class");
            label.setFont(new Font("Times New Roman", 0, 14));
            jPanel2.add(label);

            for (int i = 0; i < classes.size(); i++){

                JPanel panel = new JPanel();
                panel.setBorder(new RoundedBorder(10));
                panel.setBackground(Color.WHITE);

                JLabel className = new JLabel();
                className.setFont(new Font("Times New Roman", 1, 24)); // NOI18N
                className.setText(classes.get(i).get(1));
                className.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        int result = JOptionPane.showConfirmDialog(null, "Do You Want To Join This Class", "Question", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                        if (result == JOptionPane.YES_OPTION) {
                            try {
                                if (!studentController.checkAlreadyJoined(studentName, className.getText().trim())) {
                                    if (studentController.joinClass(studentName, className.getText().trim())) {
                                        JOptionPane.showConfirmDialog(null, "You Have Joined Class", "Success", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
                                    }
                                }
                                else{
                                    JOptionPane.showConfirmDialog(null, "You Have Already Joined This Class", "Error", JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
                                }
                            } catch (SQLException ex) {
                                throw new RuntimeException(ex);
                            }
                        }
                    }

                    @Override
                    public void mouseEntered(MouseEvent e) {
                        className.setForeground(new Color(91, 8, 136));
                    }

                    @Override
                    public void mouseExited(MouseEvent e) {
                        className.setForeground(Color.BLACK);
                    }
                });

                JLabel teacherName = new JLabel();
                teacherName.setFont(new Font("Times New Roman", 0, 18)); // NOI18N
                teacherName.setText(classes.get(i).get(0));

                JTextArea classDescription = new JTextArea();
                classDescription.setCaretColor(Color.WHITE);
                classDescription.setEditable(false);
                classDescription.setColumns(20);
                classDescription.setRows(5);
                classDescription.setLineWrap(true);
                classDescription.setText(classes.get(i).get(2));
                JScrollPane scrollPane = new JScrollPane();
                scrollPane.setViewportView(classDescription);

                JSeparator separator = new JSeparator();


                GroupLayout jPanelLayout = new GroupLayout(panel);
                panel.setLayout(jPanelLayout);
                jPanelLayout.setHorizontalGroup(
                        jPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addComponent(className, GroupLayout.PREFERRED_SIZE, 245, Short.MAX_VALUE)
                                                .addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                                                .addComponent(teacherName, GroupLayout.PREFERRED_SIZE, 215, Short.MAX_VALUE)
                                                .addComponent(separator))
                                        .addGap(18, 18, 18))
                );
                jPanelLayout.setVerticalGroup(
                        jPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(className)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(teacherName)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(separator, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23))
                );

                jPanel2.add(Box.createVerticalStrut(10));
                panel.setMaximumSize(new Dimension(jPanel2.getMaximumSize().width, 250));
                jPanel2.add(panel);

            }
        }

        pack();

    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | UnsupportedLookAndFeelException | IllegalAccessException |
                 InstantiationException ex) {
            java.util.logging.Logger.getLogger(JoinClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JoinClass("").setVisible(true);
                } catch (SQLException | ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });
    }

    // Variables declaration - do not modify
    private JLabel jLabel1;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private String studentName;
    private JScrollPane jScrollPane1;
    private StudentController studentController;
    // End of variables declaration
}
