package Views;

import Controllers.TeacherController;

import javax.swing.*;
import java.sql.SQLException;

public class Reply extends JFrame {

    public Reply(int commentId) throws SQLException, ClassNotFoundException {
        this.commentId = commentId;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() throws SQLException, ClassNotFoundException {

        jScrollPane1 = new JScrollPane();
        ReplyField = new JTextArea();
        ReplyButton = new JButton();

        teacherController = new TeacherController();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SeeReply");
        setResizable(false);

        ReplyField.setColumns(20);
        ReplyField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ReplyField.setLineWrap(true);
        ReplyField.setRows(5);
        jScrollPane1.setViewportView(ReplyField);

        ReplyButton.setBackground(new java.awt.Color(148, 11, 146));
        ReplyButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ReplyButton.setForeground(new java.awt.Color(255, 255, 255));
        ReplyButton.setText("Reply");
        ReplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    ReplyButtonActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                        .addComponent(ReplyButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ReplyButton)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void ReplyButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {

        if (!ReplyField.getText().trim().isEmpty()){

            String reply = ReplyField.getText().trim();
            if (teacherController.reply(commentId, reply)){
                JOptionPane.showConfirmDialog(null, "Replied To The Comment Successfully", "Success", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
        }
        else{
            JOptionPane.showConfirmDialog(null, "Fill Out the Reply Field", "Error", JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | UnsupportedLookAndFeelException | IllegalAccessException |
                 InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeeReply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Reply(0).setVisible(true);
                } catch (SQLException | ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });
    }

    // Variables declaration - do not modify
    private JButton ReplyButton;
    private JTextArea ReplyField;
    private JScrollPane jScrollPane1;
    private int commentId;
    private TeacherController teacherController;
    // End of variables declaration
}
