package Views;

import Controllers.StudentController;
import Models.ScrollPaneWin11;

import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.*;
import javax.swing.border.Border;

/**
 *
 * @author Abdul Ahad
 */
public class StudentHomeScreen extends JFrame {

    /**
     * Creates new form StudentHomeScreen
     */
    public StudentHomeScreen(String username) throws SQLException, ClassNotFoundException {
        this.username = username;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() throws SQLException, ClassNotFoundException {

        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jScrollPane1 = new ScrollPaneWin11();
        jPanel2 = new JPanel();

        studentController = new StudentController();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new Color(91, 8, 136));

        jLabel1.setFont(new Font("Snap ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new Color(255, 255, 255));
        jLabel1.setText("TechTeach");


        jLabel2.setFont(new Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new Color(255, 255, 255));
        jLabel2.setIcon(new ImageIcon(getClass().getResource("/com/scd/finalproject/icons/icons8-add-30.png"))); // NOI18N
        jLabel2.setText("Join Class");
        jLabel2.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                try {
                    jLabel2MouseClicked(evt);
                } catch (SQLException | ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 155, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 438, Short.MAX_VALUE)
                                .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setMinimumSize(new Dimension(725, 426));

        jPanel2.setBackground(new Color(255, 255, 255));
        jPanel2.setMaximumSize(new Dimension(32767, 32767));
        jPanel2.setMinimumSize(new Dimension(723, 424));
        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(jPanel2);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        HashMap<String, String> classes = studentController.getClasses(username);
        jScrollPane1.setPreferredSize(new Dimension(0, 0));
        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.PAGE_AXIS));
        //jPanel2.add(Box.createVerticalStrut(10));
        if (classes.size() >= 1) {

            for (String classname: classes.keySet()) {

                JPanel panel = new JPanel();

                panel.setPreferredSize(new Dimension(500, 100));
                panel.setMinimumSize(new Dimension(500, 100));
                panel.setMaximumSize(new Dimension(jPanel2.getMaximumSize().width, 100));
                panel.setBackground(Color.WHITE);
                panel.setLayout(new BorderLayout());

                JLabel className = new JLabel(classname);
                className.setFont(new Font("Times New Roman", 1, 24));
                JLabel teacherName = new JLabel((String)classes.get(classname));
                teacherName.setFont(new Font("Times New Roman", 0, 18));


                className.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        try {
                            Class studentClass = new Class(className.getText().trim(), teacherName.getText().trim(), username);
                            studentClass.setVisible(true);
                            studentClass.addWindowListener(new WindowAdapter() {
                                @Override
                                public void windowClosed(WindowEvent e) {
                                    dispose();
                                    try {
                                        StudentHomeScreen studentHomeScreen = new StudentHomeScreen(username);
                                        studentHomeScreen.setVisible(true);
                                    } catch (SQLException | ClassNotFoundException ex) {
                                        throw new RuntimeException(ex);
                                    }
                                }
                            });
                        } catch (SQLException | ClassNotFoundException ex) {
                            throw new RuntimeException(ex);
                        }

                    }

                    @Override
                    public void mouseEntered(MouseEvent e) {
                        className.setForeground(new Color(91, 8, 136));
                    }

                    @Override
                    public void mouseExited(MouseEvent e) {
                        className.setForeground(Color.BLACK);
                    }
                });

                teacherName.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        try {
                            Class studentClass = new Class(className.getText().trim(), teacherName.getText().trim(), username);
                            studentClass.setVisible(true);
                            studentClass.addWindowListener(new WindowAdapter() {
                                @Override
                                public void windowClosed(WindowEvent e) {
                                    dispose();
                                    try {
                                        StudentHomeScreen studentHomeScreen = new StudentHomeScreen(username);
                                        studentHomeScreen.setVisible(true);
                                    } catch (SQLException | ClassNotFoundException ex) {
                                        throw new RuntimeException(ex);
                                    }
                                }
                            });
                        } catch (SQLException | ClassNotFoundException ex) {
                            throw new RuntimeException(ex);
                        }
                    }

                    @Override
                    public void mouseEntered(MouseEvent e) {
                        teacherName.setForeground(new Color(91, 8, 136));
                    }

                    @Override
                    public void mouseExited(MouseEvent e) {
                        teacherName.setForeground(Color.BLACK);
                    }
                });

                panel.add(className, BorderLayout.BEFORE_FIRST_LINE);
                panel.add(teacherName, BorderLayout.LINE_START);
                panel.setBorder(new RoundedBorder(10));

                jPanel2.add(panel);
                jPanel2.add(Box.createVerticalStrut(10));
            }
        }
        pack();
    }// </editor-fold>

    private void jLabel2MouseClicked(MouseEvent evt) throws SQLException, ClassNotFoundException {

        JoinClass joinClass = new JoinClass(username);

        joinClass.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                try {
                    dispose();
                    StudentHomeScreen studentHomeScreen = new StudentHomeScreen(username);
                    studentHomeScreen.setVisible(true);
                } catch (SQLException | ClassNotFoundException ex) {
                    throw new RuntimeException(ex);
                }
            }
        });
        joinClass.setVisible(true);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new StudentHomeScreen("Ahad").setVisible(true);
                } catch (SQLException | ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });
    }

    class RoundedBorder implements Border {
        private int radius;

        public RoundedBorder(int radius) {
            this.radius = radius;
        }

        @Override
        public Insets getBorderInsets(Component c) {
            return new Insets(this.radius + 1, this.radius + 1, this.radius + 2, this.radius);
        }

        @Override
        public boolean isBorderOpaque() {
            return true;
        }

        @Override
        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
            g.drawRoundRect(x, y, width - 1, height - 1, radius, radius);
        }
    }

    // Variables declaration - do not modify
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JScrollPane jScrollPane1;
    private StudentController studentController;
    private String username;
    // End of variables declaration
}
