package Views;

import Controllers.StudentController;
import Models.RoundedBorder;
import Models.ScrollPaneWin11;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.ArrayList;

public class TakeQuiz extends JFrame {

    /**
     * Creates new form Quiz
     */
    public TakeQuiz(String className) throws SQLException, ClassNotFoundException {
        this.className = className;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() throws SQLException, ClassNotFoundException {

        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jScrollPane1 = new ScrollPaneWin11();
        jPanel2 = new JPanel();


        studentController = new StudentController();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Take Quiz");

        jPanel1.setBackground(new Color(91, 8, 136));

        jLabel1.setFont(new Font("Snap ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new Color(255, 255, 255));
        jLabel1.setText("TechTeach - Quizes");
        jLabel1.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel1)
                                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new Color(255, 255, 255));

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 763, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 521, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel2);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                                .addContainerGap())
        );

        ArrayList<String> quizes = studentController.getQuizes(className);

        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));

        for (int i = 0; i < quizes.size(); i++){

            JPanel panel = new JPanel();
            panel.setBackground(Color.WHITE);
            panel.setBorder(new RoundedBorder(10));
            //panel.setPreferredSize(new Dimension(jPanel2.getPreferredSize().width, 100));



            JLabel quizTitle = new JLabel();
            quizTitle.setFont(new Font("Times New Roman", 0, 14)); // NOI18N
            quizTitle.setText(quizes.get(i));
            quizTitle.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    Quiz quiz = null;
                    try {
                        quiz = new Quiz(quizTitle.getText().trim(), className);
                        quiz.setVisible(true);
                    } catch (SQLException | ClassNotFoundException ex) {
                        throw new RuntimeException(ex);
                    }

                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    quizTitle.setForeground(new Color(91, 8, 136));
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    quizTitle.setForeground(Color.BLACK);
                }
            });


            JLabel startQuiz = new JLabel();
            startQuiz.setFont(new Font("Times New Roman", 0, 14)); // NOI18N
            startQuiz.setIcon(new ImageIcon(getClass().getResource("/com/scd/finalproject/icons/icons8-quiz-30.png"))); // NOI18N
            startQuiz.setText("Start Quiz");
            startQuiz.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    Quiz quiz = null;
                    try {
                        quiz = new Quiz(quizTitle.getText().trim(), className);
                        quiz.setVisible(true);
                    } catch (SQLException | ClassNotFoundException ex) {
                        throw new RuntimeException(ex);
                    }

                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    startQuiz.setForeground(new Color(91, 8, 136));
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    startQuiz.setForeground(Color.BLACK);
                }
            });

            GroupLayout panelLayout = new GroupLayout(panel);
            panel.setLayout(panelLayout);
            panelLayout.setHorizontalGroup(
                    panelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(quizTitle, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 462, Short.MAX_VALUE)
                                    .addComponent(startQuiz, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE)
                                    .addGap(23, 23, 23))
            );
            panelLayout.setVerticalGroup(
                    panelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(quizTitle)
                                    .addGap(15, 15, 15))
                            .addGroup(panelLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(startQuiz, GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                    .addContainerGap())
            );
            jPanel2.add(Box.createVerticalStrut(10));
            panel.setMaximumSize(new Dimension(jPanel2.getMaximumSize().width, 70));
            jPanel2.add(panel);
        }
        pack();
    }// </editor-fold>

    private void jLabel1MouseClicked(MouseEvent evt) {

        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));

        for (int i = 0; i < 10; i++){
            JPanel panel = new JPanel();
            panel.setBackground(Color.WHITE);
            panel.setBorder(new RoundedBorder(10));

            JLabel quizTitle = new JLabel();
            quizTitle.setFont(new Font("Times New Roman", 0, 14)); // NOI18N
            quizTitle.setText("Quiz Title");


            JLabel startQuiz = new JLabel();
            startQuiz.setFont(new Font("Times New Roman", 0, 14)); // NOI18N
            startQuiz.setIcon(new ImageIcon(getClass().getResource("/com/scd/finalproject/icons/icons8-quiz-30.png"))); // NOI18N
            startQuiz.setText("Start Quiz");

            GroupLayout panelLayout = new GroupLayout(panel);
            panel.setLayout(panelLayout);
            panelLayout.setHorizontalGroup(
                    panelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(quizTitle, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 462, Short.MAX_VALUE)
                                    .addComponent(startQuiz, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE)
                                    .addGap(23, 23, 23))
            );
            panelLayout.setVerticalGroup(
                    panelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(quizTitle)
                                    .addGap(15, 15, 15))
                            .addGroup(panelLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(startQuiz, GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                    .addContainerGap())
            );
            jPanel2.add(panel);
        }
        jPanel2.revalidate();
        jPanel2.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | UnsupportedLookAndFeelException | IllegalAccessException |
                 InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakeQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TakeQuiz("").setVisible(true);
                } catch (SQLException | ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });
    }

    // Variables declaration - do not modify
    private JLabel jLabel1;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JScrollPane jScrollPane1;
    private String className;
    private StudentController studentController;
    // End of variables declaration
}
